server:
  port: 8080

spring:
  application:
    name: global-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo
  stream:
    bindings:
      enrichLogMessage-in-0:
        destination: queue.log.messages
      enrichLogMessage-out-0:
        destination: queue.pretty.log.messages